### ISSUE TITLE
Protect app assets from pre-rendered screens

### ISSUE THREAD

**Issue by patrickberkeley** [ef4/prember#3]
Question on your plan for prember and potential features:

* Would it be possible to not include the full app's assets in the pre-rendered pages? Similar to https://github.com/robwebdev/ember-cli-staticboot#includeclientscripts

The use case is to protect the full app assets from users that are not authenticated. Not sending the assets is obviously not failsafe, but it would be a simple first step (simpler than splitting the app into engines, addons, another ember app, /login on a non-ember page, etc.).

**Comment by ef4** [comment]
I think that could make a good separate addon. I see it as a different concern from what prember is doing.

In general I prefer to compose more addons together rather than continue to add many options to one. In this particular case, that would be relatively straightforward: the other addon just needs to declare that it runs after prember and use the `postProcess` hook to do the html mangling.

That would have the benefit of also being able to work on html files from any source, not just prember.

**Comment by patrickberkeley** [comment]
✅ Thanks for your thoughts!
