### ISSUE TITLE
[Micro-RFC] A CLI helper command for improved developer experience

### ISSUE THREAD

**Issue by heycarsten** [ef4/prember#35]
Hi Edward 👋 

I am absolutely loving Prember! Thank you so much for putting in all the work on this, I don't take it for granted and it has been an absolute joy so far building my new personal page with it.

While I've been using it, I made a little Bash/Shell function to sort of help with my dev experience:

```bash
prember() {
  eval "PREMBER=true npx ember $@"
}

alias prem="prember"
```

Then when I want to use a Prember-ified Ember server or issue a build, I can just:

```bash
$ prem s
```

_- OR -_

```bash
$ prem build -prod
```

Anyways, I absolutely love this project and this (albeit small thing) has removed a little friction from my process. Take care 💪

**Comment by ef4** [comment]
Thanks.

Is the issue here that you often need to do _development_ builds with prember enabled? Because for production builds it's already on by default.

And a normal `ember s` will run with fastboot on by default, so in that mode you are pretty authentically testing the real prember experience. You're just avoiding re-rendering every single page during every build.

**Comment by heycarsten** [comment]
I’m just going to close this then @ef4, thanks for your time!
