### ISSUE TITLE
Q: tidying source 

### ISSUE THREAD

**Issue by basz** [ef4/prember#5]
Hello, I’m experimenting with using the ember build tools to generate static html. Via fastboot and prember the app still ‘boots’ and everything seems to work. “When you do ember build --environment=production, your built app will include fastboot-rendered HTML”. 

So great. Howwever now I’m looking at horrible formatted html… I guess nobody would ever really care about this in live ember apps or for crawlers, but would it possible to tidy up the source before outputting it? I'm intending to use it as starting point for dreamweaver like editors... (yeah, i know...)

**Comment by basz** [comment]
ps. I think any `id="ember229"` may be removed too. my app bootsfine when manually removed.

**Comment by ef4** [comment]
I think that would make a fine separate addon. It can be told to run after prember to get the effect you want.

**Comment by basz** [comment]
Could you point me in the right direction to get started on that? No so experienced with addon authoring...

**Comment by ef4** [comment]
You can start by copying and renaming prember. Then change the `build` function so that it does HTML formatting instead of calling fastboot. Key bits:

1. [A postprocessTree method](https://github.com/ef4/prember/blob/16d0ec2224d96ff9d014898d9d3d795c8703873f/index.js#L10) that modifies the "all" tree.

2. [A broccoli plugin with a build function](https://github.com/ef4/prember/blob/16d0ec2224d96ff9d014898d9d3d795c8703873f/lib/prerender.js#L30) that reads `this.inputPaths` and writes `this.outputPath`. This is where you would call some HTML formatter.

3. Configure your addon [to run after](https://github.com/ef4/prember/blob/16d0ec2224d96ff9d014898d9d3d795c8703873f/package.json#L57-L59) prember.

**Comment by basz** [comment]
note to self: this one seems to able to do the work

**Comment by basz** [comment]
I've got something that does formatting. With options from the ember-cli-build.js. Just not sure what to put in the build method.

I would some how need to read the input, get source, apply prettifier and put on the output. It can't be hard but I have no clue how to start. Would you care to have a stab?

```
async build() {
    let formatted = html.prettyPrint('<h2><strong><a href="http://awesome.com">AwesomeCom</a></strong><span>is awesome</span></h2>', this.options);

    this.ui.writeLine(`prember-beautify ${formatted} ${chalk.green('OK')}`);
}
```
outputs
```
prember-beautify <h2>
  <strong><a href="http://awesome.com">AwesomeCom</a>
  </strong>
  <span>is awesome</span>
</h2> OK
```

**Comment by basz** [comment]
https://github.com/basz/prember-beautify

not published yet

**Comment by basz** [comment]
I just published it on NPM, so `ember install prember-beautify` should work…
