### ISSUE TITLE
Title tags not respected in generated statics

### ISSUE THREAD

**Issue by basz** [ef4/prember#6]
Per advise of the fast boot add-on i'm using https://github.com/kimroen/ember-cli-document-title to set titles. In the running app this is respected, but not in the outputted static html...

Haven't tested the other addons to set other meta tags, but I'm guessing those aren't respected either...

**Comment by ef4** [comment]
As far as I can tell, ember-cli-document-title doesn't [really work right with fastboot](https://github.com/kimroen/ember-cli-document-title/issues/45) unless you also use ember-cli-head, and follow [these instructions](https://github.com/kimroen/ember-cli-document-title#use-with-ember-cli-head).

This is not caused by prember, you can verify by running your app under fastboot without prember and you'll see that titles are missing there too.

I just added [some test coverage](https://github.com/ef4/prember/blob/7c2ac2a7f852cd4be12370b8a55af9ae4f6e21a4/node-tests/basic-test.js) to verify that we can definitely set `<title>` and `<meta>` tags from within prember.
